### ISSUE TITLE
invalid configuration

### ISSUE THREAD

**Issue by almereyda** [njnygaard/kubectl-multiforward#4]
With the file `~/.multiforward.yaml` as:

```yaml
groups:
  - name: next
    services:
      - displayName: Alertmanager
        port: 9093
        namespace: kube-prometheus-stack
        name: alertmanager-operated
        protocol: http
      - displayName: Prometheus
        port: 9090
        namespace: kube-prometheus-stack
        name: prometheus-operated
        protocol: http
      - displayName: Grafana
        port: 3000
        namespace: kube-prometheus-stack
        name: kube-prometheus-stack-grafana
        protocol: http
      - displayName: Argo CD
        port: 443
        namespace: argocd
        name: argocd-server
        protocol: http

      # This needs a deployment of Hubble UI and associated ClusterIP service
      # - displayName: Hubble
      #   port: 9200
      #   namespace: cilium
      #   name: 
      #   protocol: https

      # This needs a separate internal ClusterIP Service
      # In https://doc.traefik.io/traefik/getting-started/install-traefik/#exposing-the-traefik-dashboard
      # they use an IngressRoute, which is by default not secure, and cannot be forwarded here
      # - displayName: Traefik
      #   port: 9000
      #   namespace: traefik
      #   name: traefik
```

and having this installed through `kubectl krew install multiforward`, we get the error:

```shell
invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

while access to the cluster is working as expected:

```shell
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7", GitCommit:"b56e432f2191419647a6a13b9f5867801850f969", GitTreeState:"archive", BuildDate:"2022-03-01T00:00:00Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"c1de2d70269039fe55efb98e737d9a29f9155246", GitTreeState:"clean", BuildDate:"2022-07-13T14:19:57Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
```

How could I possibly debug this?

---

The commented parts in the YAML manifest are related to:

- https://github.com/njnygaard/kubectl-multiforward/issues/3
