### ISSUE TITLE
krew registry installs old version of the plugin?

### ISSUE THREAD

**Issue by dmitry-mightydevops** [njnygaard/kubectl-multiforward#9]
```
➜ k krew install multiforward
...
➜ k multiforward prod                                             
remote port must be > 0
remote port must be > 0
remote port must be > 0
```

my config file:

```yaml
➜ cat .multiforward.yaml                                                   
# https://github.com/njnygaard/kubectl-multiforward/blob/master/.multiforward.example.yaml
# https://github.com/njnygaard/kubectl-multiforward
groups:
  - name: prod
    services:
      - displayName: prometheus
        localPort: 9090
        servicePort: 9090
        namespace: prometheus
        name: prometheus-prometheus
        protocol: http
      - displayName: grafana
        localPort: 8080
        servicePort: 80
        namespace: grafana
        name: grafana
        protocol: http
      - displayName: argocd
        localPort: 7070
        servicePort: 80
        namespace: argo-cd
        name: argo-cd-argocd-server
        protocol: http

```
